### ISSUE TITLE
Sosivio 1.6.0 breaks on MicroK8s 1.27

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/microk8s-community-addons#156]
#### Summary
The latest 1.6.0 release of sosivio seems to be failing on MicroK8s.

When enabling the addon the communicator pod is crashlooping with the following error: 

```
ubuntu@ip-172-31-3-156:~$ sudo microk8s.kubectl logs -n sosivio       pod/communicator-8588f8b5b6-cbb2d
{
        "name": "communicator",
        "nodeName": "ip-172-31-3-156",
        "podName": "communicator-8588f8b5b6-cbb2d",
        "podNamespace": "sosivio",
        "podIP": "10.1.118.200",
        "podUUID": "058d54a6-c63e-4ecf-ac28-d98721638efb",
        "host": "communicator-8588f8b5b6-cbb2d",
        "port": "8082",
        "startedAt": "2023-07-14T12:18:17.199926044Z",
        "serverTime": "2023-07-14T12:18:17.498859370Z",
        "build": {
                "branch": "release-1.6.0",
                "commit": "7d4513b",
                "builtAt": "2023-07-12T13:15:19.945550195Z"
        }
}
panic: GetNSQDNodes() failed: error HttpCall() failed: error performHttpCall() failed: Get "http://nsqlookupd:4161/nodes": dial tcp: lookup nsqlookupd on 10.152.183.10:53: no such host

goroutine 1 [running]:
main.main()
        /app/internal/cmd/app/main.go:27 +0x7fb
```

#### What Should Happen Instead?
The addon should deploy without problems.

#### Reproduction Steps

Install microk8s and follow the sosivio steps to deploy the 1.6.0 release. 

#### Introspection Report

[inspection-report-20230714_122628.tar.gz](https://github.com/canonical/microk8s-community-addons/files/12050359/inspection-report-20230714_122628.tar.gz)

**Comment by DanArlowski** [comment]
@ktsakalozos 

Thanks!
We will release a 1.6.1 version to solve that shortly.

should i create a PR to remove the pin?

thanks,
Dan
