### ISSUE TITLE
kwasm dropping crun causes tests to fail

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/microk8s-community-addons#180]
#### Summary
The In the latest kwasm node installer the crun support was removed https://github.com/KWasm/kwasm-node-installer/releases . The kwasm operator uses the latest kwasm-node-installer and as a result the validation tests started failing.

#### What Should Happen Instead?
The addon should deploy a specific version of the operator and by extension use a specific version of the kwasm-node-installer. This way stable MicroK8s releases are not affected by similar changes breaking backwards compatibility.

Furthermore, when a user deploys a stable MicroK8s branch or has an automation that includes the kwasm addon he does not want to  all of a sudden get a different behavior.

#### Can you suggest a fix?
As an immediate mitigation I am going to disable the kwasm validation and testing in all affected branches so our CI is not blocked. 

@0xE282B0 would you please be able to address this issue by pining the version of kwasm shipped in the addon on each affected branch?

**Comment by 0xE282B0** [comment]
Hi @ktsakalozos,
I'm sorry for the inconvenience. I didn't realize the impact on the microk8s plugin.

I'll pin the installer and operator versions.
