### ISSUE TITLE
Update cloudnative-pg addon to version 1.22.0 and add addon arg to specifiy version

### ISSUE THREAD

**Issue by TecIntelli** [canonical/microk8s-community-addons#217]
#### Summary
I would like to use cloudnative-pg in the latest version 1.22.0. Unfortunately in the currently provided MicroK8s addon is the version 1.21.1 hard-coded.
Please, could the maintainer of the addon or somebody else update the variable  `CNPG_VERSION` in the `enable` file to `1.22.0`.

Further I would suggest that the version should be passed as an addon argument like I have seen in the [core addon dns](https://github.com/canonical/microk8s-core-addons/blob/main/addons/dns/enable).

#### Why is this important?
Not just for security reasons it would be very helpful to use the lastest version of a third party package. Further the possibility to choose the best fitting version individually would offer a better chance to test new versions or skip buggy versions.

#### Are you interested in contributing to this feature?
I would suggest to change line 4 in file `microk8s-community-addons/addons/cloudnative-pg/enable` into:
```
CNPG_VERSION="$1"
if [ -z "$1" ]; then
        CNPG_VERSION="1.22.0"
```
(not tested yet)

Thanks, I appreciate your effort!

**Comment by neoaggelos** [comment]
Hi @TecIntelli, contributions are welcome, I've added a `good-first-issue` and `help-wanted` labels.
