### ISSUE TITLE
Addon Request: WasmEdge

### ISSUE THREAD

**Issue by 0xE282B0** [canonical/microk8s-community-addons#27]
With crun and WasmEdge it is possible to execute runtimeless WebAssembly container images. Like described [here](https://wasmedge.org/book/en/kubernetes.html). 

### WasmEdge
Crun can be compiled with WebaAssembly support to run `*.wasm` files. That takes the distroless approach one step further and moves even the runtime out of the container image. That makes images smaller and reduces the attack surface of the image even more.
Since crun is an alternative runtime it can be added to containerd like the kata runtime and the add-on installs the runtime as snap and sets it as deflault in the `enable` script.

Next steps:
- [x] ~~Add crun to microk8s containerd config~~
- [x] Package crun runtime as snap https://github.com/0xE282B0/crun-wasmedge-snap
- [x] Create enable/disable scrips

**Comment by AlexsJones** [comment]
Thank you for your contribution @ktsakalozos will take a look and get back to you with any questions and how to progress
