### ISSUE TITLE
Istio PodDisruptionBudgets' version is unavailable in v1.25+

### ISSUE THREAD

**Issue by benjaminxie** [canonical/microk8s-community-addons#90]
#### Summary
Enabling Istio, I get errors like 
```
Istiod encountered an error: failed to update resource with server-side apply for obj PodDisruptionBudget/istio-system/istiod: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```
Note that the version is the deprecated policy/v1beta1 and not policy/v1.
#### What Should Happen Instead?
I should not get this error. MKS should install Istio with PodDisruptionBudgets with version policy/v1.

#### Reproduction Steps

1. Use MicroK8s v1.25.2 revision 4055 (or probably just anything v1.25+)
2. Run ```microk8s enable istio```

#### Introspection Report
Will supply if actually needed.

#### Can you suggest a fix?
Use Istio version v1.14+ instead of v1.10.3

#### Are you interested in contributing with a fix?
Perhaps in a few months.

**Comment by ktsakalozos** [comment]
Hi @benjaminxie thank you for reporting this. He have a PR from a community member https://github.com/canonical/microk8s-community-addons/pull/85 to address these issues but it seems it has gone stale. Are you interested in taking it over?

**Comment by neoaggelos** [comment]
PR is merged, closing the issue.
