### ISSUE TITLE
openEBS version bump for microk8s 1.25 cluster

### ISSUE THREAD

**Issue by zacbayhan** [canonical/microk8s-community-addons#96]
#### Summary
Openebs jiva storage class fails due to a v1betav1 error when using it on k8's 1.25, I was able to fix this by bumping the version up to 3.2.x. What would be nice is that pvc replicas were scaled to the number of nodes in the cluster. 

#### Why is this important?
I believe this is important for smaller clusters, it seems that in a two node development cluster the 3rd replica would never establish and prevent the service that requested the pvc to to bind the pvc to the pv. I was able to fix this by scaling the stateful set to 2. My proposed fix would be in the enable script,  set the number of replicas of the stateful set to the number of nodes in the cluster, Also if  the number of nodes in the cluster is greater than 1, I would run an additional command which patches the jiva storage class to be default storageclass. 

#### Are you interested in contributing to this feature?
yes, please let me know if I can help.

**Comment by zacbayhan** [comment]
created pull request https://github.com/canonical/microk8s-community-addons/pull/103/commits/605232ca9056f8c1d3bc3f5b2643b76ed89b44b8

**Comment by djjudas21** [comment]
Looks like there are two separate issues being addressed here, but the version bump is essential because the OpenEBS addon can't start up in Kubernetes 1.25

**Comment by zacbayhan** [comment]
The issue has been resolved with merged pr 

https://github.com/canonical/microk8s-community-addons/pull/103#
